### ISSUE TITLE
add roGridScreen in PosterScreen.brs

### ISSUE THREAD

**Issue by xoceunder** [paulwhiting/GospelLibraryVideos#1]
as could add roGridScreen in PosterScreen.brs

**Comment by paulwhiting** [comment]
@xoceunder I'm sorry I didn't respond sooner.  For some reason I wasn't notified about the issue you submitted.  What exactly are you asking for?  Do you want me to replace all of the poster screens with grid screens or just particular ones?  I don't know how well that would work out due to the highly nested structure of the content.

**Comment by xoceunder** [comment]
add GridScreen since you have ADDED ListScreen and PosterScreen

to have 3 types different style

**Comment by xoceunder** [comment]
@paulwhiting hello friend Might help to implement the GridScreen style

**Comment by paulwhiting** [comment]
I just pushed a new version with grid screen support.

**Comment by xoceunder** [comment]
@paulwhiting and how to activate the screen grid

**Comment by xoceunder** [comment]
@paulwhiting now everything is Grid Screen Print Screen is no longer displayed

**Comment by xoceunder** [comment]
@paulwhiting  could contact me directly to make a request

xoceunder@gmail.com

**Comment by paulwhiting** [comment]
Closed as implemented.  Further work will be tracked in #5.
